config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :tweets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'tweets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.all.order('created_at DESC')
    @tweet = Tweet.new
  end

  # GET /tweets/1 or /tweets/1.json
  def show; end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.build
  end

  # GET /tweets/1/edit
  def edit; end

  # POST /tweets or /tweets.json
  def create
    @tweet = current_user.tweets.build(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_url(@tweet), notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tweet_params
    params.require(:tweet).permit(:tweet)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_active?(url_path)
    if current_page?(url_path)
      'font-bold'
    else
      ''
    end
  end

  def is_active_logo?(url_path)
    if current_page?(url_path)
      'currentColor'
    else
      'none'
    end
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://unpkg.com/twemoji@14.0.2/dist/twemoji.min.js" integrity="sha384-ICOlZarapRIX6UjKPcWKEpubjg7lGADN7Y9fYP4DU9zm0aPFhgnP5ef+XFaPyKv+" crossorigin="anonymous"></script>
    <title>TweeterClone</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class='relative'>
    <div class='xl:w-10/12 w-11/12 mx-auto flex'>
      <nav class='xl:w-[276px] w-[88px] h-screen sticky top-0 flex flex-col gap-1.5 xl:items-start xl:px-8 items-center py-4 font-semibold'>
        <%= link_to root_path, :action => 'go' do %>
        <div class='mb-2'>
          <img class='w-[59px] h-[59px] rounded-full py-2.5 px-3 hover:bg-gray-400/30' src="https://i.ibb.co/YfNX8Ty/download.png" alt="logo">
        </div>
        <% end %>
        <section class='flex flex-col gap-1.5 xl:items-start items-center font-semibold'>
          <%= link_to root_path, :action => 'go' do %>
              <div class="flex gap-4 items-center rounded-full px-4 py-3 justify-center hover:bg-gray-400/30">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-7 h-7">
                  <path fill-rule="evenodd" d="M9.493 2.853a.75.75 0 00-1.486-.205L7.545 6H4.198a.75.75 0 000 1.5h3.14l-.69 5H3.302a.75.75 0 000 1.5h3.14l-.435 3.148a.75.75 0 001.486.205L7.955 14h2.986l-.434 3.148a.75.75 0 001.486.205L12.456 14h3.346a.75.75 0 000-1.5h-3.14l.69-5h3.346a.75.75 0 000-1.5h-3.14l.435-3.147a.75.75 0 00-1.486-.205L12.045 6H9.059l.434-3.147zM8.852 7.5l-.69 5h2.986l.69-5H8.852z" clip-rule="evenodd" />
                </svg>

                <p class="text-xl xl:block hidden <%= is_active?(root_path) %> ">Explore</p>
              </div>
          <% end %>
        </section>
        <% if user_signed_in? %>
          <section class='flex flex-col gap-1.5 xl:items-start items-center font-semibold'>
            <%= link_to root_path, :action => 'go' do %>
              <div class="flex gap-4 items-center rounded-full px-4 py-3 justify-center hover:bg-gray-400/30">
                <svg xmlns="http://www.w3.org/2000/svg" fill="<%= is_active_logo?(root_path) %>" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-7 h-7">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12l8.954-8.955c.44-.439 1.152-.439 1.591 0L21.75 12M4.5 9.75v10.125c0 .621.504 1.125 1.125 1.125H9.75v-4.875c0-.621.504-1.125 1.125-1.125h2.25c.621 0 1.125.504 1.125 1.125V21h4.125c.621 0 1.125-.504 1.125-1.125V9.75M8.25 21h8.25" />
                </svg>
                <p class="text-xl xl:block hidden <%= is_active?(root_path) %> ">Home</p>
              </div>
              
            <% end %>
            <%= link_to tweets_path, :action => 'go' do %>
              <div class='flex gap-4 items-center justify-center rounded-full px-4 py-3 hover:bg-gray-400/30'>
                <svg xmlns="http://www.w3.org/2000/svg" fill="<%= is_active_logo?(tweets_path) %>" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-7 h-7">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z" />
                </svg>

                <p class='text-xl xl:block hidden <%= is_active?(tweets_path) %>'>Profile</p>
              </div>
            <% end %>
            <div class="flex flex-col">
              <%= link_to new_tweet_path, :action => 'go' do %>
                <div class="bg-sky-500 xl:px-14 xl:py-2.5 rounded-full hover:bg-sky-600 flex items-center justify-center p-2 mt-2">
                  <p class="text-gray-50 font-semibold text-base xl:inline hidden">Woff</p>
                  <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2.5" stroke="currentColor" class="w-7 h-7 xl:hidden inline text-white">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
                  </svg>
                </div>
              <% end %>
              <%= button_to destroy_user_session_path, method: :delete do %>
                <div class="bg-red-400 xl:px-12 xl:py-2.5 rounded-full hover:bg-red-500 flex items-center justify-center p-2 mt-2">
                  <p class="text-gray-50 font-semibold text-base xl:inline hidden">Logout</p>
                </div>
              <% end %>
            </div>
          </section>
        <% end %>
      </nav>

      <% if flash[:notice] %>
        <div class="p-4 mb-4 text-sm text-green-800 rounded-lg bg-green-50" role="alert">
          <%= notice %>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="p-4 mb-4 text-sm text-blue-800 rounded-lg bg-blue-50" role="alert">
          <%= alert %>
        </div>
      <% end %>

      <%= yield %>

      <section class="w-[34rem] flex flex-col items-center py-2.5 gap-6">
        <div class='rounded-full bg-gray-100 z-10 sticky top-2.5 w-10/12 py-0.5 pl-2 flex items-center justify-around'>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 group-active:text-sky-500 h-6 text-gray-500">
            <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z" />
          </svg>
          <input type="text" class='focus:outline-none bg-transparent py-1.5 w-10/12 placeholder:text-gray-500' placeholder='Search Twitter'>
        </div>
        <div class="rounded-xl z-0 bg-gray-200/70 w-10/12 h-[80vh] animate-pulse"></div>
      </section>
    
    </div>
    <% if not user_signed_in? %>
      <section class="flex absolute bottom-0 bg-sky-500 w-full py-3 justify-center text-white">
        <div class="flex items-center justify-between w-[54rem]">
          <div class="">
            <p class="text-2xl font-bold">Don't miss what's is happening</p>
            <p class="text-md">People on Woff are the first to know.</p>
          </div>
          <div class="flex gap-3 items-start">
            <%= link_to 'Log in', new_user_session_path, class:'bg-sky-500 border text-whit font-bold rounded-full hover:bg-white/20 pt-1.5 pb-2.5 px-4' %>
            <%= link_to 'Sign up', new_user_registration_path, class:'bg-white text-black font-medium rounded-full hover:bg-gray-100 pt-1.5 pb-2.5 px-4' %>
          </div>
        </div>
      </section>
    <% end %>
  </body>
</html>

app/views/tweets/_feed.html.erb
<% @tweets.each do | woff | %>
  <div class='border-t pl-4 hover:bg-gray-100/60 ease-in-out duration-200'>
    <div class='flex gap-3 py-3'>
      <img class='w-12 h-12 rounded-full' src="https://miro.medium.com/v2/resize:fill:176:176/1*YPkv2C4dj1uCFH4IctmrCA.png" alt="Profile Picture">
      <div class="flex flex-col gap-0.5 w-full pr-5">
        <nav class="flex w-full justify-between">
          <div class="flex items-center gap-1">
            <p class="font-bold"><%= woff.user.name %></p>
            <p class="text-sm text-gray-700/80">@<span><%= woff.user.username %></span></p>
          </div>
        </nav>
        <div class="flex flex-col gap-3.5">
          <p class="pr-7 text-black/90">
            <%= woff.tweet %>
          </p>
          <div class="flex items-center gap-2">
            <%= button_to tweet_path(woff), title:'Delete', method: :delete, data: { confirmation: "Are you sure?", turbo_confirm: "Are you sure?" }, class:'text-gray-700/40 hover:text-red-500' do %>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
              </svg>
            <% end %>
            <%= link_to edit_tweet_path(woff), title:'Edit', class:'text-gray-700/40 hover:text-sky-500' do %>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L6.832 19.82a4.5 4.5 0 01-1.897 1.13l-2.685.8.8-2.685a4.5 4.5 0 011.13-1.897L16.863 4.487zm0 0L19.5 7.125" />
              </svg>
            <% end %>
            <%= link_to woff, title:'Woff', class:'text-gray-700/40 hover:text-sky-500' do %>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                <path stroke-linecap="round" stroke-linejoin="round" d="M18.375 12.739l-7.693 7.693a4.5 4.5 0 01-6.364-6.364l10.94-10.94A3 3 0 1119.5 7.372L8.552 18.32m.009-.01l-.01.01m5.699-9.941l-7.81 7.81a1.5 1.5 0 002.112 2.13" />
              </svg>
            <% end %>

          </div>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex flex-col">
    <div class="my-5">
      <%= form.text_area :tweet, autofocus: true, placeholder:"What's happening?", class: "resize-none overflow-hidden block text-lg bg-transparent placeholder:text-black/60 placeholder:text-xl outline-none px-3 w-full" %>
    </div>

    <div class="inline self-end">
      <%= form.submit "Woff" , class: "bg-sky-500 text-white font-medium rounded-full hover:bg-sky-600 py-1.5 px-5" %>
    </div>
  </div>

<% end %>

app/views/tweets/_tweet.html.erb
<div class='border-t pl-4 hover:bg-gray-100/60 ease-in-out duration-200'>
    <div class='flex gap-3 py-3'>
        <img class='w-12 h-12 rounded-full' src="https://miro.medium.com/v2/resize:fill:176:176/1*YPkv2C4dj1uCFH4IctmrCA.png" alt="Profile Picture">
        <div class="flex flex-col gap-0.5 w-full pr-5">
        <nav class="flex w-full justify-between">
            <div class="flex items-center gap-1">
                <p class="font-bold">Halim Shams</p>
                <p class="text-sm text-gray-700/80">@<span>HalimOFFI</span></p>
            </div>
        </nav>
        <p class="pr-7 text-black/90">
            <%= @tweet.tweet %>
        </p>
        </div>
    </div>
</div>

app/views/tweets/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing tweet</h1>

  <%= render "form", tweet: @tweet %>

  <%= link_to "Show this tweet", @tweet, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to tweets", tweets_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/tweets/index.html.erb
<div class="w-[50rem] border-x">
  <div class="px-4 py-6 sticky top-0 bg-white/70 backdrop-blur-md border-b">
    <% if user_signed_in? %>
      <h1 class="font-bold text-2xl">Home</h1>
    <% else %>
      <h1 class="font-bold text-2xl">Explore</h1>
    <% end %>
  </div>
  <% if user_signed_in? %>
    <div class='px-4 pt-3 pb-3'>
      <%= render "form", tweet: @tweet %>
    </div>
  <% end %>

  <div id="tweets" class="min-w-full">
    <%= render 'feed' %>
  </div>
</div>

app/views/tweets/new.html.erb
<div class="w-full">
  <h1 class="font-bold text-2xl">Compouse a new Tweet</h1>

  <%= render "form", tweet: @tweet %>

  <%= link_to 'Back to tweets', tweets_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/tweets/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto w-full">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @tweet %>
  </div>
</div>